FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    sshpass \
    openssh-client \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN pip3 install --upgrade pip setuptools wheel && \
    pip3 install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /home/ansible/project

CMD ["tail", "-f", "/dev/null"]