FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    sshpass \
    openssh-client \
    python3 \
    python3-pip \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file from your laptop into the container build context
COPY requirements.txt /tmp/requirements.txt

# Install all Python dependencies from the file
RUN pip3 install --upgrade pip && \
    pip3 install -r /tmp/requirements.txt

WORKDIR /home/ansible/project

CMD ["tail", "-f", "/dev/null"]