---
# Define a group named 'webservers'
webservers:
  hosts:
    node_01:
      ansible_host: 10.99.0.11
      ansible_user: root
      ansible_ssh_pass: root
    node_02:
      ansible_host: 10.99.0.12
      ansible_user: root
      ansible_ssh_pass: root

# Define the built-in 'all' group to apply global settings
all:
  vars:
    # Bypassing strict host key checking for the lab environment
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'